### ISSUE TITLE
Bad Code

### ISSUE THREAD

**Issue by Dsummers91** [zhenpanda/ethsf_confer#1]
Git gud

**Comment by zhenpanda** [comment]
wat?

**Comment by Dsummers91** [comment]
I recommend ``` rm -rf ./```

**Comment by dutchmartin** [comment]
Maybe describing what needs to be done is more practical.

**Comment by Dsummers91** [comment]
It's a joke issue, we're at a hackathon together :smile_cat: @dutchmartin
